apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santa
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: boubkar/santa:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: santa-ssvc
spec:
  selector:
    app: santa
  ports:
    - protocol: "TCP"
      port: 8080        # Le port auquel le service est exposé dans le cluster
      targetPort: 8080   # Le port auquel le conteneur écoute
      nodePort: 32076    # Port externe via NodePort (si LoadBalancer ne fonctionne pas)
  type: NodePort         # Utilisation de NodePort pour exposer le service à l'extérieur
  externalTrafficPolicy: Cluster  # Pour conserver l'adresse IP d'origine
